---
- name: Read public key from local file
  slurp:
    src: "{{ ssh_public_key_file }}"
  register: pub_key_content
  delegate_to: localhost
  run_once: yes

- name: Add public key to target user's authorized_keys
  authorized_key:
    user: "{{ ssh_user }}"
    state: present
    key: "{{ pub_key_content['content'] | b64decode }}"
